apiVersion: v1
kind: ConfigMap
metadata:
  name: --APP_NAME--
data:
  RDBMS_URL: jdbc:mariadb:failover://mariadb-galera-0.galera-cluster.mariadb-galera.svc:3306,mariadb-galera-1.galera-cluster.mariadb-galera.svc:3306,mariadb-galera-2.galera-cluster.mariadb-galera.svc:3306/home_librarian
  CORS_ORIGINS: "*"
