spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: --APP_NAME--
        resources:
          requests:
            memory: 500Mi
            cpu:    500m
          limits:
            memory: 500Mi
            cpu:    1
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 1
      terminationGracePeriodSeconds: 15